config/routes.rb
Taggr::Application.routes.draw do |map|
  match 'train/', :to => 'classifier#train', :via => 'post', :as => 'train'
  match 'train/', :to => 'classifier#create_train', :via => 'get'

  match 'try-guess/', :to => 'classifier#try_guess', :via => 'get', :as => 'try_guess'
  match 'guess/', :to => 'classifier#create_guess', :via => 'get'
  match 'guess/', :to => 'classifier#guess', :via => 'post', :as => 'guess'
  
  match 'reports/:initial_date/:end_date/:percentage', :to => 'reports#report', :via => 'get', :as => 'reports'
  match 'reports/', :to => 'reports#create', :via => 'get'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :tag
  validates_presence_of :date, :percentage, :related_link
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :name
  has_many :entries
  
  def self.report_by_percentage(initial_date, end_date, min_percentage)
    Tag.all(
      :select => 'name, count(entries.id) as total',    
      :joins => :entries,
      :conditions => ["entries.date between ? and ? and entries.percentage >= ?", initial_date, end_date, min_percentage.to_f/100],
      :group => 'name'
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/classifier_controller.rb
class ClassifierController < ApplicationController
  def train
    classifier = BayesianClassifier.new    
    
    params[:tags].split(',').each do |tag|
      classifier.train tag, params[:content]
    end
    
    respond_to do |response|
      response.html
      response.xml { head :ok }
    end
  end
  
  def create_train
    @tags = Tag.find(:all)
    
    respond_to do |response|
      response.html
      response.xml { render :xml => @tags, :status => :ok }
    end
  end

  def try_guess
    classifier = BayesianClassifier.new  
    guesses = classifier.guess(params[:content])
    
    @result = Hash.new
    
    guesses.each do |guess|
      tag = Tag.find(guess[0].to_i)
      @result[tag.name.to_s] = guess[1]
    end
    
    respond_to do |response|
      response.json { render :json => @result, :status => :ok } 
    end
  end
  
  def create_guess
  end
  
  def guess
    classifier = BayesianClassifier.new  
    guesses = classifier.guess(params[:content])
    
    @result = Hash.new
    
    guesses.each do |guess|
      tag = Tag.find(guess[0].to_i)
      tag.entries << (Entry.new :date => params[:date], :related_link => params[:related_link], :percentage => guess[1])
      tag.save!
      
      @result[tag.name.to_s] = guess[1]
    end
    
    respond_to do |response|
      response.html
      response.xml { render :xml => @result, :status => :ok } 
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def report
    @tags = Tag.report_by_percentage params[:initial_date], params[:end_date], params[:percentage]
    @total = @tags.inject(0) { |sum, e| sum + e.total }
  end
  
  def create
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifier_helper.rb
module ClassifierHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/classifier/create_guess.html.erb
<form action="<%= guess_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
	<label for="content">Content:</label>
	<textarea name="content"></textarea>
	<label for="date">Date:</label>
	<input type="text" name="date" />
	<label for="related_link">Related Link:</label>
	<input type="text" name="related_link" />
	
	<input type="submit" value="Guess!" />
</form>

app/views/classifier/create_train.html.erb
<form action="<%= train_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
	<label for="content">Content:</label>
	<textarea name="content" id="content"></textarea>
	<label for="tag">Tag:</label>
	<% for tag in @tags %>
	<input type="checkbox" name="tags" value="<%= tag.id %>" /><%= tag.name %>
	<% end %>
	
	<input type="button" value="Try guess" id="try_guess" action="<%= try_guess_url %>" />
	<input type="submit" value="Train!" />
</form>

<div id="try_guess_response">

</div>

<script type="text/javascript">
	function guessed(data) {
		var response = "";
		$.each(data, function(i,n){
			response += i + "=" + n + "%<br/>";
		});
		$('#try_guess_response').html(response);
	}

	$('#try_guess').click(function() {
		var action = $(this).attr('action');
		$.get(action, { content : $('#content').val() }, guessed); 
	});
</script>

app/views/classifier/guess.html.erb
guessed!

<% @result.each do |k,v| %>
	<%= k %>=<%= v*100%>%
<% end %>

app/views/classifier/train.html.erb
trained!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taggr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min' %>
  <%= javascript_include_tag 'highcharts' %>
<!--[if IE]>
  <%= javascript_include_tag 'excanvas.compiled' %>
<![endif]-->
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/create.html.erb
<script type="text/javascript">
	$(function(){
		$('#report_submit').click(function() {
			var form = $('#report_form');
			location.href = form.attr('action') + '/' + $('#initial_date').val() + '/' + $('#end_date').val() + "/" + $('#percentage').val()
		});
	});
</script>

<form method="get" action="<%= reports_url %>" id="report_form">
	Initial Date: <input type="textbox" name="initial_date" id="initial_date">
	End Date: <input type="textbox" name="end_date" id="end_date">
	Min Percentage: <input type="textbox" name="percentage" id="percentage">
	<input type="button" value="Generate report" id="report_submit" />
</form>

app/views/reports/report.html.erb
<%
data = ''
for tag in @tags
	data = data + "['#{tag.name}', #{tag.total/@total*100}],"
end
%>
<script type="text/javascript">
var chart;

$(function() {
var chart = new Highcharts.Chart({
   chart: {
      renderTo: 'container',
      margin: [50, 200, 60, 170]
   },
   title: {
      text: 'Tags Report'
   },
   plotArea: {
      shadow: null,
      borderWidth: null,
      backgroundColor: null
   },
   tooltip: {
      formatter: function() {
         return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
      }
   },
   plotOptions: {
      pie: {
         allowPointSelect: true,
         dataLabels: {
            enabled: true,
            formatter: function() {
               if (this.y > 5) return this.point.name;
            },
            color: 'white',
            style: {
               font: '13px Trebuchet MS, Verdana, sans-serif'
            }
         }
      }
   },
   legend: {
      layout: 'vertical',
      style: {
         left: 'auto',
         bottom: 'auto',
         right: '50px',
         top: '100px'
      }
   },
        series: [{
      type: 'pie',
      name: 'Tags',
      data: [<%= data.chop %>]
   }]
});
});
</script>
<h1>Report</h1>
<div id="container"></div>
<div id="summary">
	<% for tag in @tags %>
	<%= tag.name%>=<%= tag.total %>
	<% end %>
	total: <%= @total%>
</div>